### ISSUE TITLE
debug notes

### ISSUE THREAD

**Issue by caver456** [ncssar/gpsio#32]
A lot of parts have to be talking with each other, in multiple browsers on multiple platforms.  These debug notes are meant to deal with 'layers of the onion'.  On the surface of the onion, the file transfers should work: gpx should be exported and imported as expected.  If a given 'layer' doesn't appear to be functioning, dig down to the next layer using the notes here, until the issue is found.

- clicking extension icon only gives red line 'Cannot communicate with host'
-- make sure the new extension (v1.0+) is installed, and the old extension (v<1.0) is removed

- running host executable (specified in host manifest) from command line gives errors (you will have to type some stuff in, since it reads stdin)
```
PS C:\Program Files (x86)\GPSIO> .\dist\python.exe gpsio-host.py
asdfasdf
Traceback (most recent call last):
  File "C:\Program Files (x86)\GPSIO\gpsio-host.py", line 470, in <module>
    Main()
  File "C:\Program Files (x86)\GPSIO\gpsio-host.py", line 124, in Main
    request_length = struct.unpack('i', request_length_bytes)[0]
TypeError: a bytes-like object is required, not 'str'
PS C:\Program Files (x86)\GPSIO>
```

-- make sure the host has the lines to reopen stdin and stdout in bytes mode:
```
if sys.platform == "win32":
    import msvcrt
    try:
        sys.stdout=os.fdopen(sys.stdout.fileno(), 'wb')
        sys.stdin=os.fdopen(sys.stdin.fileno(), 'rb', 0)
        msvcrt.setmode(sys.stdin.fileno(), os.O_BINARY)
        msvcrt.setmode(sys.stdout.fileno(), os.O_BINARY)
    except Exception as e:
        sys.exit("ABORT: "+str(e)+"\nMaybe this script is being run from the command line with no arguments?  If so, this abort is expected.  Use it from the web browser extension.")
```

try this

**Comment by caver456** [comment]
this issue was intended to be an ongoing set of notes.  A better media for that type of thing is google drive, so all development and debug notes from now on should go to: 

https://docs.google.com/document/d/1kgK_XLCWkqEsnX-RVMVUbcaq9VT6KtjqoBKprnkkba4/edit?usp=sharing
